# Generated by Django 3.2.4 on 2021-06-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='runnig_time',
            new_name='running_time',
        ),
    ]
